In [1]:
import numpy as np

In [86]:
arr = [[1,2,3.9], [4,5,6], [7,8,9]]

In [87]:
a = np.array(arr)
a

array([[1. , 2. , 3.9],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]])

In [90]:
print(a.ndim)
print(a.shape)
print(a.dtype)

2
(3, 3)
float64


In [18]:
zeros = np.zeros((3,4))
ones = np.ones((4,5))
identity = np.identity(5)
random = np.random.random((4,7))

print(f"zeros = {zeros}"), print(f"ones = {ones}"), print(f"identity = {identity}"), print(f"random = {random}")
type(zeros)

zeros = [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones = [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
identity = [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
random = [[0.10824593 0.97654138 0.09773643 0.36212854 0.41856591 0.57699048
  0.00981885]
 [0.25393875 0.83280758 0.10689863 0.23722792 0.60972084 0.04064447
  0.65453303]
 [0.4753885  0.66620196 0.79762201 0.47494077 0.84442361 0.49275167
  0.54970179]
 [0.15717915 0.06810297 0.76957376 0.7658535  0.26621812 0.7790146
  0.63868487]]


numpy.ndarray

In [20]:
c = [[21,4,6], [5,7,9], [3,7,8]]
d = [[3,6,9], [5,6,8], [5,7,1]]
e = [[6,9,0], [4,5,2], [7,3,4]]
cc = np.array(c)
dd = np.array(d)
ee = np.array(e)

In [21]:
print(cc + dd + ee)

[[30 19 15]
 [14 18 19]
 [15 17 13]]


In [27]:
print(cc)

[[21  4  6]
 [ 5  7  9]
 [ 3  7  8]]


In [28]:
print(ee**ee)

[[    46656 387420489         1]
 [      256      3125         4]
 [   823543        27       256]]


In [29]:
d[2]

[5, 7, 1]

In [30]:
dd[2]

array([5, 7, 1])

In [33]:
dd[2,2]

6

In [34]:
dd

array([[3, 6, 9],
       [5, 6, 8],
       [5, 7, 1]])

In [37]:
dd[:2, :2]

array([[3, 6],
       [5, 6]])

In [35]:
dd[[0,2,1],[2,0,2]] # array([9,5,8]) -50+35+5

array([9, 5, 8])

In [46]:
np.linalg.det(dd)

104.99999999999997

In [41]:
dd[0].sum()

18

In [44]:
dd.mean()

5.555555555555555

In [42]:
dd.sum()

50

In [45]:
dd.std()

2.3147407395555177

In [47]:
np.save('ddarray',dd)

In [49]:
np.savetxt('ddarraytxt.txt',dd)

In [52]:
dd_load = np.load('ddarray.npy')

In [54]:
print(dd_load)

[[3 6 9]
 [5 6 8]
 [5 7 1]]


In [55]:
dd == dd_load

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [56]:
dd[0,2]

9

In [57]:
dd_clone = dd
print(dd_clone)

[[3 6 9]
 [5 6 8]
 [5 7 1]]


In [58]:
dd_clone[0,2] = 4
print(dd_clone)

[[3 6 4]
 [5 6 8]
 [5 7 1]]


In [59]:
dd_clone == dd

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [60]:
print(dd_clone)
print(dd)

[[3 6 4]
 [5 6 8]
 [5 7 1]]
[[3 6 4]
 [5 6 8]
 [5 7 1]]


In [61]:
dd_clone2 = dd_clone[:]
print(dd_clone)
print(dd_clone2)

[[3 6 4]
 [5 6 8]
 [5 7 1]]
[[3 6 4]
 [5 6 8]
 [5 7 1]]


In [62]:
dd_clone2[0,1] = 7
print(dd_clone)
print(dd_clone2)

[[3 7 4]
 [5 6 8]
 [5 7 1]]
[[3 7 4]
 [5 6 8]
 [5 7 1]]


In [63]:
print(dd)

[[3 7 4]
 [5 6 8]
 [5 7 1]]


In [65]:
kk = np.array([[5,7,9], [0,5,2], [3,7,1]])
print(kk)

[[5 7 9]
 [0 5 2]
 [3 7 1]]


In [66]:
kk_clone = kk[:]

In [68]:
kk_clone[1,1] = 8

In [69]:
print(kk)
print(kk_clone)

[[5 7 9]
 [0 8 2]
 [3 7 1]]
[[5 7 9]
 [0 8 2]
 [3 7 1]]


In [70]:
print(kk)

[[5 7 9]
 [0 8 2]
 [3 7 1]]


In [71]:
print(kk_clone)

[[5 7 9]
 [0 8 2]
 [3 7 1]]


In [72]:
print(np.loadtxt('ddarraytxt.txt'))

[[3. 6. 9.]
 [5. 6. 8.]
 [5. 7. 1.]]


In [73]:
print(np.load('ddarray.npy'))

[[3 6 9]
 [5 6 8]
 [5 7 1]]


In [91]:
list1 = [4,7,2]

In [92]:
list1_alias = list1

In [93]:
print(list1)
print(list1_alias)

[4, 7, 2]
[4, 7, 2]


In [94]:
list1_alias[1] = 9

In [95]:
print(list1)
print(list1_alias)

[4, 9, 2]
[4, 9, 2]


In [96]:
list1_clone = list1[:]

In [97]:
print(list1)
print(list1_clone)

[4, 9, 2]
[4, 9, 2]


In [98]:
list1_clone[2] = 5

In [99]:
print(list1)
print(list1_clone)

[4, 9, 2]
[4, 9, 5]


In [103]:
s = np.array(['Jan', 'Feb', 'Mar'])
s
print(s)
print(s.dtype)

['Jan' 'Feb' 'Mar']
<U3


In [104]:
import pandas as pd
ss = pd.Series(s, index =['a', 'b', 'c'])

In [124]:
pd.DataFrame([])

Empty DataFrame
Columns: []
Index: []

In [ ]:
print(ss)
print(ss.dtype

In [ ]:
#create a dataframe of 5 players (name, country, club, position, goals) with a list and dictionary

In [108]:
#list
players_list = [['Messi','Argentina','PSG','Forward',750],
                ['Ronaldo','Portugal','Al-Nassr','Forward',800],
                ['Neymar','Brazil','PSG','Forward',500],
                ['Modric','Croatia','Real Madrid','Midfielder',150],
                ['T.Silva','Brazil','Chelsea','Defender',50]]

players_dict = {
                    'Name':['Messi','Ronaldo','Neymar','Modric','T.Silva'],
                    'Country':['Argentina','Portugal','Brazil','Croatia','Brazil'],
                    'Club':['PSG','Al-Nassr','PSG','Real Madrid','Chelsea'],
                    'Position':['Forward','Forward','Forward','Midfielder','Defender'],
                    'Goals':[750,800,500,150,50]
               }

In [109]:
df_list = pd.DataFrame(players_list, columns=['Name','Country','Club','Position','Goals'])
df_dict = pd.DataFrame(players_dict)

In [112]:
print(df_list)
print('=============================================================')
print(df_dict)

      Name    Country         Club    Position  Goals
0    Messi  Argentina          PSG     Forward    750
1  Ronaldo   Portugal     Al-Nassr     Forward    800
2   Neymar     Brazil          PSG     Forward    500
3   Modric    Croatia  Real Madrid  Midfielder    150
4  T.Silva     Brazil      Chelsea    Defender     50
      Name    Country         Club    Position  Goals
0    Messi  Argentina          PSG     Forward    750
1  Ronaldo   Portugal     Al-Nassr     Forward    800
2   Neymar     Brazil          PSG     Forward    500
3   Modric    Croatia  Real Madrid  Midfielder    150
4  T.Silva     Brazil      Chelsea    Defender     50


In [116]:
df_dict.to_excel('players_dict.xlsx')
df_list.to_csv('players_list.csv')
df_dict.to_json('players_dict.json')

In [120]:
print(df_list.iloc[3,3]) #used to index by row index and column index
print(df_list.loc[0,'Goals']) #used to index by row number and column header

Midfielder
750


In [121]:
#logic is same as iloc and loc indexing
print(df_dict.iat[2,1])
print(df_dict.at[4,'Club'])

Brazil
Chelsea


In [ ]:
#Data type and wrangling

In [125]:
url = 'https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv?raw=true'

In [126]:
fuel_data = pd.read_csv(url,error_bad_lines=False)

In [127]:
fuel_data.shape

(29523, 11)

In [132]:
fuel_data.tail(50)

record_id  utility_id_ferc1  report_year  \
29473  f1_fuel_2018_12_193_0_13               193         2018   
29474  f1_fuel_2018_12_193_0_15               193         2018   
29475   f1_fuel_2018_12_193_1_1               193         2018   
29476   f1_fuel_2018_12_193_1_5               193         2018   
29477   f1_fuel_2018_12_193_1_7               193         2018   
29478   f1_fuel_2018_12_193_1_9               193         2018   
29479  f1_fuel_2018_12_193_1_10               193         2018   
29480  f1_fuel_2018_12_193_1_12               193         2018   
29481  f1_fuel_2018_12_193_1_15               193         2018   
29482    f1_fuel_2018_12_80_0_2                80         2018   
29483    f1_fuel_2018_12_80_0_5                80         2018   
29484    f1_fuel_2018_12_80_0_6                80         2018   
29485    f1_fuel_2018_12_80_0_8                80         2018   
29486    f1_fuel_2018_12_80_0_9                80         2018   
29487   f1_fuel_2018_12_80_0_11                80         2018   
29488   f1_fuel_2018_12_80_0_12                80         2018   
29489   f1_fuel_2018_12_80_0_14                80         2018   
29490   f1_fuel_2018_12_80_0_15                80         2018   
29491    f1_fuel_2018_12_80_1_3                80         2018   
29492   f1_fuel_2018_12_191_0_2               191         2018   
29493   f1_fuel_2018_12_191_0_3               191         2018   
29494   f1_fuel_2018_12_191_0_5               191         2018   
29495   f1_fuel_2018_12_191_0_6               191         2018   
29496   f1_fuel_2018_12_191_0_8               191         2018   
29497  f1_fuel_2018_12_191_0_11               191         2018   
29498   f1_fuel_2018_12_191_1_2               191         2018   
29499   f1_fuel_2018_12_191_1_3               191         2018   
29500   f1_fuel_2018_12_191_1_6               191         2018   
29501   f1_fuel_2018_12_191_1_8               191         2018   
29502   f1_fuel_2018_12_191_1_9               191         2018   
29503  f1_fuel_2018_12_191_1_14               191         2018   
29504  f1_fuel_2018_12_191_1_15               191         2018   
29505   f1_fuel_2018_12_432_0_2               432         2018   
29506   f1_fuel_2018_12_432_0_5               432         2018   
29507   f1_fuel_2018_12_432_0_8               432         2018   
29508  f1_fuel_2018_12_432_0_11               432         2018   
29509  f1_fuel_2018_12_432_0_14               432         2018   
29510   f1_fuel_2018_12_403_0_2               403         2018   
29511   f1_fuel_2018_12_403_0_6               403         2018   
29512   f1_fuel_2018_12_403_0_9               403         2018   
29513    f1_fuel_2018_12_12_0_2                12         2018   
29514    f1_fuel_2018_12_12_0_4                12         2018   
29515    f1_fuel_2018_12_12_0_7                12         2018   
29516    f1_fuel_2018_12_12_0_8                12         2018   
29517   f1_fuel_2018_12_12_0_10                12         2018   
29518   f1_fuel_2018_12_12_0_13                12         2018   
29519    f1_fuel_2018_12_12_1_1                12         2018   
29520   f1_fuel_2018_12_12_1_10                12         2018   
29521   f1_fuel_2018_12_12_1_13                12         2018   
29522   f1_fuel_2018_12_12_1_14                12         2018   

           plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
29473  pleasant prairie-tot                coal       ton        1232699.0   
29474  pleasant prairie-tot                 gas       mcf          81891.0   
29475    presque isle-total                coal       ton        1029238.0   
29476   pt washington-total                 gas       mcf       39905100.0   
29477            rothschild               waste       ton         369201.0   
29478            rothschild                 gas       mcf         185673.0   
29479    so oak creek-total                coal       ton        2784916.0   
29480    so oak creek-total    

In [130]:
fuel_data.describe(include='all')

record_id  utility_id_ferc1   report_year  \
count                      29523      29523.000000  29523.000000   
unique                     29523               NaN           NaN   
top     f1_fuel_2010_12_170_0_15               NaN           NaN   
freq                           1               NaN           NaN   
mean                         NaN        118.601836   2005.806050   
std                          NaN         74.178353      7.025483   
min                          NaN          1.000000   1994.000000   
25%                          NaN         55.000000   2000.000000   
50%                          NaN        122.000000   2006.000000   
75%                          NaN        176.000000   2012.000000   
max                          NaN        514.000000   2018.000000   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
count             29523               29523     29343     2.952300e+04   
unique             2315                   6         9              NaN   
top           big stone                 gas       mcf              NaN   
freq                156               11486     11354              NaN   
mean                NaN                 NaN       NaN     2.622119e+06   
std                 NaN                 NaN       NaN     9.118004e+06   
min                 NaN                 NaN       NaN     1.000000e+00   
25%                 NaN                 NaN       NaN     1.381700e+04   
50%                 NaN                 NaN       NaN     2.533220e+05   
75%                 NaN                 NaN       NaN     1.424034e+06   
max                 NaN                 NaN       NaN     5.558942e+08   

        fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
count          29523.000000               29523.000000   
unique                  NaN                        NaN   
top                     NaN                        NaN   
freq                    NaN                        NaN   
mean               8.492111                 208.649031   
std               10.600220                2854.490090   
min                0.000001                -276.080000   
25%                1.024000                   5.207000   
50%                5.762694                  26.000000   
75%               17.006000                  47.113000   
max              341.260000              139358.000000   

        fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
count                   2.952300e+04         29523.000000  
unique                           NaN                  NaN  
top                              NaN                  NaN  
freq                             NaN                  NaN  
mean                    9.175704e+02            19.304354  
std                     6.877593e+04          2091.540939  
min                    -8.749370e+02           -41.501000  
25%                     3.778500e+00             1.940000  
50%                     1.737100e+01             4.127000  
75%                     4.213700e+01             7.745000  
max                     7.964521e+06        359278.000000

In [131]:
fuel_data.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [133]:
fuel_data.groupby('fuel_unit')['fuel_unit'].count()

fuel_unit
bbl        7998
gal          84
gramsU      464
kgU         110
mcf       11354
mmbtu       180
mwdth        95
mwhth       100
ton        8958
Name: fuel_unit, dtype: int64

In [134]:
fuel_data['fuel_unit'] = fuel_data['fuel_unit'].fillna(value='mcf')

In [135]:
fuel_data.isnull().sum()

record_id                       0
utility_id_ferc1                0
report_year                     0
plant_name_ferc1                0
fuel_type_code_pudl             0
fuel_unit                       0
fuel_qty_burned                 0
fuel_mmbtu_per_unit             0
fuel_cost_per_unit_burned       0
fuel_cost_per_unit_delivered    0
fuel_cost_per_mmbtu             0
dtype: int64

In [136]:
fuel_data.groupby('report_year')['report_year'].count()

report_year
1994    1235
1995    1201
1996    1088
1997    1094
1998    1107
1999    1050
2000    1373
2001    1356
2002    1205
2003    1211
2004    1192
2005    1269
2006    1243
2007    1264
2008    1228
2009    1222
2010    1261
2011    1240
2012    1243
2013    1199
2014    1171
2015    1093
2016    1034
2017     993
2018     951
Name: report_year, dtype: int64

In [138]:
fuel_data.groupby('fuel_type_code_pudl')['fuel_type_code_pudl'].count()

fuel_type_code_pudl
coal        8547
gas        11486
nuclear      818
oil         8064
other        167
waste        441
Name: fuel_type_code_pudl, dtype: int64

In [137]:
fuel_data.groupby('fuel_type_code_pudl').first()b

record_id  utility_id_ferc1  report_year  \
fuel_type_code_pudl                                                          
coal                  f1_fuel_1994_12_1_0_7                 1         1994   
gas                  f1_fuel_1994_12_2_0_10                 2         1994   
nuclear               f1_fuel_1994_12_2_1_1                 2         1994   
oil                   f1_fuel_1994_12_6_0_2                 6         1994   
other                f1_fuel_1994_12_11_0_6                11         1994   
waste                 f1_fuel_1994_12_9_0_3                 9         1994   

                     plant_name_ferc1 fuel_unit  fuel_qty_burned  \
fuel_type_code_pudl                                                
coal                         rockport       ton        5377489.0   
gas                         chickasaw       mcf          40533.0   
nuclear              joseph m. farley       kgU           2260.0   
oil                      clinch river       bbl           6510.0   
other                      w.f. wyman       bbl          55652.0   
waste                    b.l. england       ton           2438.0   

                     fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
fuel_type_code_pudl                                                   
coal                           16.590000                     18.590   
gas                             1.000000                      2.770   
nuclear                         0.064094                     28.770   
oil                             5.875338                     32.130   
other                           0.149719                     14.685   
waste                           0.015939                     34.180   

                     fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
fuel_type_code_pudl                                                     
coal                                       18.530                1.121  
gas                                         2.770                2.570  
nuclear                                     0.000                0.450  
oil                                        23.444                5.469  
other                                      15.090                2.335  
waste                                      34.180                1.072

In [143]:
fuel_data_1 = fuel_data.iloc[0:19000].reset_index(drop=True)
fuel_data_2 = fuel_data.iloc[19000:].reset_index(drop=True)

In [144]:
fuel_data_1

record_id  utility_id_ferc1  report_year  \
0         f1_fuel_1994_12_1_0_7                 1         1994   
1        f1_fuel_1994_12_1_0_10                 1         1994   
2         f1_fuel_1994_12_2_0_1                 2         1994   
3         f1_fuel_1994_12_2_0_7                 2         1994   
4        f1_fuel_1994_12_2_0_10                 2         1994   
...                         ...               ...          ...   
18995   f1_fuel_2009_12_182_1_9               182         2009   
18996  f1_fuel_2009_12_182_1_10               182         2009   
18997  f1_fuel_2009_12_182_1_13               182         2009   
18998  f1_fuel_2009_12_182_1_14               182         2009   
18999    f1_fuel_2009_12_79_0_1                79         2009   

           plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0                  rockport                coal       ton        5377489.0   
1      rockport total plant                coal       ton       10486945.0   
2                    gorgas                coal       ton        2978683.0   
3                     barry                coal       ton        3739484.0   
4                 chickasaw                 gas       mcf          40533.0   
...                     ...                 ...       ...              ...   
18995             lake road                 gas       mcf         340857.0   
18996             lake road                 oil       mcf            771.0   
18997           iatan (18%)                coal       ton         414142.0   
18998           iatan (18%)                 oil       bbl           5761.0   
18999              montrose                coal       ton        2050919.0   

       fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0                16.590000                     18.590   
1                16.592000                     18.580   
2                24.130000                     39.720   
3                23.950000                     47.210   
4                 1.000000                      2.770   
...                    ...                        ...   
18995             1.000000                      4.711   
18996             5.801544                     84.899   
18997            16.718000                     18.509   
18998             5.537910                     83.636   
18999            17.160000                     29.629   

       fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                            18.530                1.121  
1                            18.530                1.120  
2                            38.120                1.650  
3                            45.990                1.970  
4                             2.770                2.570  
...                             ...                  ...  
18995                         4.711                4.711  
18996                        84.899               14.634  
18997                        17.570                1.107  
18998                        72.280               15.102  
18999                        28.330                1.727  

[19000 rows x 11 columns]

In [145]:
fuel_data_2

record_id  utility_id_ferc1  report_year  \
0       f1_fuel_2009_12_79_0_2                79         2009   
1       f1_fuel_2009_12_79_0_4                79         2009   
2       f1_fuel_2009_12_79_0_5                79         2009   
3       f1_fuel_2009_12_79_0_7                79         2009   
4      f1_fuel_2009_12_79_0_10                79         2009   
...                        ...               ...          ...   
10518  f1_fuel_2018_12_12_0_13                12         2018   
10519   f1_fuel_2018_12_12_1_1                12         2018   
10520  f1_fuel_2018_12_12_1_10                12         2018   
10521  f1_fuel_2018_12_12_1_13                12         2018   
10522  f1_fuel_2018_12_12_1_14                12         2018   

           plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0                  montrose                 oil       bbl          22912.0   
1                hawthorn 5                coal       ton        2408123.0   
2                hawthorn 5                 gas       mcf          82141.0   
3            hawthorn 6 & 9                 gas       mcf        1701680.0   
4            hawthorn 7 & 8                 gas       mcf          82601.0   
...                     ...                 ...       ...              ...   
10518    neil simpson ct #1                 gas       mcf          18799.0   
10519  cheyenne prairie 58%                 gas       mcf         806730.0   
10520     lange ct facility                 gas       mcf         104554.0   
10521       wygen 3 bhp 52%                coal       ton         315945.0   
10522       wygen 3 bhp 52%                 gas       mcf          17853.0   

       fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0                 5.770422                     65.443   
1                16.782000                     18.598   
2                 1.000000                      6.238   
3                 1.000000                      4.885   
4                 1.000000                      5.383   
...                    ...                        ...   
10518             1.059000                      4.780   
10519             1.050000                      3.650   
10520             1.060000                      4.770   
10521            16.108000                      3.060   
10522             1.059000                      0.000   

       fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                            67.540               11.341  
1                            18.310                1.108  
2                             6.238                6.238  
3                             4.885                4.885  
4                             5.383                5.383  
...                             ...                  ...  
10518                         4.780                9.030  
10519                         3.650                6.950  
10520                         4.770                8.990  
10521                        14.760                1.110  
10522                         0.000               11.680  

[10523 rows x 11 columns]

In [152]:
#check if the sum of the two new groups are equal to fuel_data sum
assert len(fuel_data) == len(fuel_data_1) + len(fuel_data_2), 'the summations are not equal'

In [155]:
#merging and joins
fuel_data_inner = pd.merge(fuel_data_1,fuel_data_2,how='inner') #join records that are same for both dataset (intersection)
fuel_data_inner

Empty DataFrame
Columns: [record_id, utility_id_ferc1, report_year, plant_name_ferc1, fuel_type_code_pudl, fuel_unit, fuel_qty_burned, fuel_mmbtu_per_unit, fuel_cost_per_unit_burned, fuel_cost_per_unit_delivered, fuel_cost_per_mmbtu]
Index: []

In [156]:
fuel_data_inner.shape

(0, 11)

In [157]:
fuel_data_outer = pd.merge(fuel_data_1,fuel_data_2,how='outer') #join records from both dataset (union)
fuel_data_outer

record_id  utility_id_ferc1  report_year  \
0        f1_fuel_1994_12_1_0_7                 1         1994   
1       f1_fuel_1994_12_1_0_10                 1         1994   
2        f1_fuel_1994_12_2_0_1                 2         1994   
3        f1_fuel_1994_12_2_0_7                 2         1994   
4       f1_fuel_1994_12_2_0_10                 2         1994   
...                        ...               ...          ...   
29518  f1_fuel_2018_12_12_0_13                12         2018   
29519   f1_fuel_2018_12_12_1_1                12         2018   
29520  f1_fuel_2018_12_12_1_10                12         2018   
29521  f1_fuel_2018_12_12_1_13                12         2018   
29522  f1_fuel_2018_12_12_1_14                12         2018   

           plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0                  rockport                coal       ton        5377489.0   
1      rockport total plant                coal       ton       10486945.0   
2                    gorgas                coal       ton        2978683.0   
3                     barry                coal       ton        3739484.0   
4                 chickasaw                 gas       mcf          40533.0   
...                     ...                 ...       ...              ...   
29518    neil simpson ct #1                 gas       mcf          18799.0   
29519  cheyenne prairie 58%                 gas       mcf         806730.0   
29520     lange ct facility                 gas       mcf         104554.0   
29521       wygen 3 bhp 52%                coal       ton         315945.0   
29522       wygen 3 bhp 52%                 gas       mcf          17853.0   

       fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0                   16.590                      18.59   
1                   16.592                      18.58   
2                   24.130                      39.72   
3                   23.950                      47.21   
4                    1.000                       2.77   
...                    ...                        ...   
29518                1.059                       4.78   
29519                1.050                       3.65   
29520                1.060                       4.77   
29521               16.108                       3.06   
29522                1.059                       0.00   

       fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                             18.53                1.121  
1                             18.53                1.120  
2                             38.12                1.650  
3                             45.99                1.970  
4                              2.77                2.570  
...                             ...                  ...  
29518                          4.78                9.030  
29519                          3.65                6.950  
29520                          4.77                8.990  
29521                         14.76                1.110  
29522                          0.00               11.680  

[29523 rows x 11 columns]

In [158]:
#removes right dataset records not present in left dataset (leftdataset - right dataset ==> differencebb)
fuel_data_left = pd.merge(fuel_data_1,fuel_data_2,how='left') 
fuel_data_left

record_id  utility_id_ferc1  report_year  \
0         f1_fuel_1994_12_1_0_7                 1         1994   
1        f1_fuel_1994_12_1_0_10                 1         1994   
2         f1_fuel_1994_12_2_0_1                 2         1994   
3         f1_fuel_1994_12_2_0_7                 2         1994   
4        f1_fuel_1994_12_2_0_10                 2         1994   
...                         ...               ...          ...   
18995   f1_fuel_2009_12_182_1_9               182         2009   
18996  f1_fuel_2009_12_182_1_10               182         2009   
18997  f1_fuel_2009_12_182_1_13               182         2009   
18998  f1_fuel_2009_12_182_1_14               182         2009   
18999    f1_fuel_2009_12_79_0_1                79         2009   

           plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0                  rockport                coal       ton        5377489.0   
1      rockport total plant                coal       ton       10486945.0   
2                    gorgas                coal       ton        2978683.0   
3                     barry                coal       ton        3739484.0   
4                 chickasaw                 gas       mcf          40533.0   
...                     ...                 ...       ...              ...   
18995             lake road                 gas       mcf         340857.0   
18996             lake road                 oil       mcf            771.0   
18997           iatan (18%)                coal       ton         414142.0   
18998           iatan (18%)                 oil       bbl           5761.0   
18999              montrose                coal       ton        2050919.0   

       fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0                16.590000                     18.590   
1                16.592000                     18.580   
2                24.130000                     39.720   
3                23.950000                     47.210   
4                 1.000000                      2.770   
...                    ...                        ...   
18995             1.000000                      4.711   
18996             5.801544                     84.899   
18997            16.718000                     18.509   
18998             5.537910                     83.636   
18999            17.160000                     29.629   

       fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                            18.530                1.121  
1                            18.530                1.120  
2                            38.120                1.650  
3                            45.990                1.970  
4                             2.770                2.570  
...                             ...                  ...  
18995                         4.711                4.711  
18996                        84.899               14.634  
18997                        17.570                1.107  
18998                        72.280               15.102  
18999                        28.330                1.727  

[19000 rows x 11 columns]

In [159]:
fuel_data.duplicated().any()

False